site_name: Science Informatique - Site en construction
docs_dir: docs

site_url: https://mmarchand-nsi.github.io

draft_docs: |
  première/prog/tuples.md
  terminale/langages/calculabilite.md

copyright: Matthieu Marchand


theme:
  name: material
  logo: assets/logo-tr.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.path
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - logic
  - search
  - git-revision-date-localized
  - autorefs
  - sqlite-console


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - mkdocs_graphviz
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: logic    
          class: logic
          format: !!python/name:logic_superfence.formatter
          validator: !!python/name:logic_superfence.validator

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - javascripts/myglobal.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://mkdocs-logic.forge.apps.education.fr/javascripts/bundle.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

